services:
  db:
    image: postgres:16.2
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=stream-tide
      - POSTGRES_DB=stream-tide-db
    ports:
      - 5454:5432
    volumes:
      - ./db-data:/var/lib/postgresql/data

# NODE_ENV=development
# DB_HOST=localhost
# DB_USER=bytedash
# DB_PASSWORD=supersecret
# DB_NAME=bytedash
# DB_PORT=5432


